# Generated by Django 6.0.4 on 2026-09-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('programme_type', models.CharField(choices=[('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=20)),
                ('capacity_limit', models.PositiveIntegerField(default=50)),
            ],
            options={
                'unique_together': {('course_code', 'programme_type')},
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_name', models.CharField(max_length=50)),
                ('academic_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('intake_name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=200)),
                ('programme_type', models.CharField(choices=[('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.intake')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_letters', to='admissions.student')),
            ],
        ),
    ]
