# Generated by Django 6.1 on 2026-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionletter',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admissionletter',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admissionletter',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionletter',
            name='status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_generated', max_length=20),
        ),
    ]
