# Generated by Django 6.1 on 2026-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionletter_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionletter',
            name='student_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
